-- MySQL Script generated by MySQL Workbench
-- 03/10/17 19:41:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sasystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sasystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sasystem` DEFAULT CHARACTER SET utf8 ;
USE `sasystem` ;

-- -----------------------------------------------------
-- Table `sasystem`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Department` (
  `Department_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Department_code` VARCHAR(255) NOT NULL COMMENT '',
  `Department_description` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Department_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Employee` (
  `Emp_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Department_id` INT NOT NULL COMMENT '',
  `Emp_last_name` VARCHAR(255) NOT NULL COMMENT '',
  `Emp_first_name` VARCHAR(255) NOT NULL COMMENT '',
  `Emp_middle_name` VARCHAR(255) NOT NULL COMMENT '',
  `Email` VARCHAR(255) NOT NULL COMMENT '',
  `Address` VARCHAR(255) NOT NULL COMMENT '',
  `Postal_code` INT(4) NOT NULL COMMENT '',
  `Tel_num` INT(6) NOT NULL COMMENT '',
  `Mobile_num` INT(11) NOT NULL COMMENT '',
  `Gender` VARCHAR(255) NOT NULL COMMENT '',
  `Civil_status` VARCHAR(255) NOT NULL COMMENT '',
  `Birth_date` DATE NOT NULL COMMENT '',
  `Birth_place` VARCHAR(255) NOT NULL COMMENT '',
  `Religion` VARCHAR(255) NOT NULL COMMENT '',
  `TIN_num` INT(12) NOT NULL COMMENT '',
  PRIMARY KEY (`Emp_id`)  COMMENT '',
  INDEX `fk_Employee_Department2_idx` (`Department_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Employee_Department2`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`Department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Reservation_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Reservation_header` (
  `Reservation_header_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Emp_id` INT NOT NULL COMMENT '',
  `Department_id` INT NOT NULL COMMENT '',
  `No_of_student_assistant` INT NOT NULL COMMENT '',
  `Scope_of_work` VARCHAR(255) NOT NULL COMMENT '',
  `Date_created` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`Reservation_header_id`)  COMMENT '',
  INDEX `fk_Reservation_header_Employee1_idx` (`Emp_id` ASC)  COMMENT '',
  INDEX `fk_Reservation_header_Department2_idx` (`Department_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Reservation_header_Employee1`
    FOREIGN KEY (`Emp_id`)
    REFERENCES `sasystem`.`Employee` (`Emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_header_Department2`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`Department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Student` (
  `Student_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Student_last_name` VARCHAR(255) NOT NULL COMMENT '',
  `Student_first_name` VARCHAR(255) NOT NULL COMMENT '',
  `Student_middle_name` VARCHAR(255) NOT NULL COMMENT '',
  `Birth_date` DATE NOT NULL COMMENT '',
  `Birth_place` VARCHAR(255) NOT NULL COMMENT '',
  `Entry_level` VARCHAR(255) NOT NULL COMMENT '',
  `Nationality` VARCHAR(255) NOT NULL COMMENT '',
  `Gender` VARCHAR(255) NOT NULL COMMENT '',
  `Address` VARCHAR(255) NOT NULL COMMENT '',
  `Postal_code` INT(4) NOT NULL COMMENT '',
  `Tel_num` INT(6) NOT NULL COMMENT '',
  `Mobile_num` INT(11) NOT NULL COMMENT '',
  `Email` VARCHAR(255) NOT NULL COMMENT '',
  `Religion` VARCHAR(255) NOT NULL COMMENT '',
  `Civil_status` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Student_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Term` (
  `Term_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `school_year` YEAR NOT NULL COMMENT '',
  `Term_num` INT(1) NOT NULL COMMENT '',
  `Term_start` DATE NOT NULL COMMENT '',
  `Term_end` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`Term_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Scholarship` (
  `Scholarship_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  `Scholarship_code` VARCHAR(255) NOT NULL COMMENT '',
  `Scholarship_description` VARCHAR(255) NOT NULL COMMENT '',
  `Scholarship_group` VARCHAR(255) NOT NULL COMMENT '',
  `Discount` DECIMAL NOT NULL COMMENT '',
  `Waive_fee` TEXT(50) NOT NULL COMMENT '',
  `Scholarship_apply` VARCHAR(255) NOT NULL COMMENT '',
  `Required_GPA` DECIMAL NOT NULL COMMENT '',
  `SA_hours` DECIMAL NOT NULL COMMENT '',
  `Program_apply` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Scholarship_id`)  COMMENT '',
  INDEX `fk_Scholarship_Student1_idx` (`Student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Scholarship_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `sasystem`.`Student` (`Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Degree` (
  `Degree_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  `Degree_code` VARCHAR(255) NOT NULL COMMENT '',
  `Degree_description` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Degree_id`)  COMMENT '',
  INDEX `fk_Degree_Student1_idx` (`Student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Degree_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `sasystem`.`Student` (`Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Specialization` (
  `Specialization_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  `Specialization_code` VARCHAR(255) NOT NULL COMMENT '',
  `Specialization_description` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Specialization_id`)  COMMENT '',
  INDEX `fk_Specialization_Student1_idx` (`Student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Specialization_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `sasystem`.`Student` (`Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Student_assistant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Student_assistant` (
  `Student_assistant_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  `Term_id` INT NOT NULL COMMENT '',
  `Degree_id` INT NOT NULL COMMENT '',
  `Specialization_id` INT NOT NULL COMMENT '',
  `Student_assistant_hours` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Student_assistant_id`)  COMMENT '',
  INDEX `fk_Student_assistant_Term1_idx` (`Term_id` ASC)  COMMENT '',
  INDEX `fk_Student_assistant_Student1_idx` (`Student_id` ASC)  COMMENT '',
  INDEX `fk_Student_assistant_Degree1_idx` (`Degree_id` ASC)  COMMENT '',
  INDEX `fk_Student_assistant_Specialization1_idx` (`Specialization_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Student_assistant_Term1`
    FOREIGN KEY (`Term_id`)
    REFERENCES `sasystem`.`Term` (`Term_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_assistant_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `sasystem`.`Student` (`Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_assistant_Degree1`
    FOREIGN KEY (`Degree_id`)
    REFERENCES `sasystem`.`Degree` (`Degree_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_assistant_Specialization1`
    FOREIGN KEY (`Specialization_id`)
    REFERENCES `sasystem`.`Specialization` (`Specialization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`SA_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`SA_record` (
  `Record_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Emp_id` INT NOT NULL COMMENT '',
  `Department_id` INT NOT NULL COMMENT '',
  `Student_assistant_id` INT NOT NULL COMMENT '',
  `Record_time_in` DATETIME NOT NULL COMMENT '',
  `Record_time_out` DATETIME NOT NULL COMMENT '',
  `Scope_of_work` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Record_id`)  COMMENT '',
  INDEX `fk_SA_record_Employee1_idx` (`Emp_id` ASC)  COMMENT '',
  INDEX `fk_SA_record_Department1_idx` (`Department_id` ASC)  COMMENT '',
  INDEX `fk_SA_record_Student_assistant1_idx` (`Student_assistant_id` ASC)  COMMENT '',
  CONSTRAINT `fk_SA_record_Employee1`
    FOREIGN KEY (`Emp_id`)
    REFERENCES `sasystem`.`Employee` (`Emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SA_record_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`Department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SA_record_Student_assistant1`
    FOREIGN KEY (`Student_assistant_id`)
    REFERENCES `sasystem`.`Student_assistant` (`Student_assistant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Request` (
  `Request_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Department_id` INT NOT NULL COMMENT '',
  `Student_assistant_id` INT NOT NULL COMMENT '',
  `Date_request` DATE NOT NULL COMMENT '',
  `Time_in` DATETIME NOT NULL COMMENT '',
  `Time_out` DATETIME NOT NULL COMMENT '',
  `Date_created` DATE NOT NULL COMMENT '',
  `Is_approved` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Request_id`)  COMMENT '',
  INDEX `fk_Request_Department2_idx` (`Department_id` ASC)  COMMENT '',
  INDEX `fk_Request_Student_assistant2_idx` (`Student_assistant_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Request_Department2`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`Department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Student_assistant2`
    FOREIGN KEY (`Student_assistant_id`)
    REFERENCES `sasystem`.`Student_assistant` (`Student_assistant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`Reservation_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`Reservation_details` (
  `Reservation_details_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Reservation_header_id` INT NOT NULL COMMENT '',
  `Student_assistant_id` INT NOT NULL COMMENT '',
  `Date_reserved` DATETIME NOT NULL COMMENT '',
  `Time_in` DATETIME NOT NULL COMMENT '',
  `Time_out` DATETIME NOT NULL COMMENT '',
  `Is_approved` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Reservation_details_id`)  COMMENT '',
  INDEX `fk_Reservation_details_Reservation_header2_idx` (`Reservation_header_id` ASC)  COMMENT '',
  INDEX `fk_Reservation_details_Student_assistant2_idx` (`Student_assistant_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Reservation_details_Reservation_header2`
    FOREIGN KEY (`Reservation_header_id`)
    REFERENCES `sasystem`.`Reservation_header` (`Reservation_header_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_details_Student_assistant2`
    FOREIGN KEY (`Student_assistant_id`)
    REFERENCES `sasystem`.`Student_assistant` (`Student_assistant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasystem`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`department` (
  `Department_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Department_code` (255) NOT NULL COMMENT '',
  `Department_description` (255) NOT NULL COMMENT '',
  PRIMARY KEY (`Department_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`employee` (
  `Emp_id` INT(11) NOT NULL COMMENT '',
  `Emp_last_name` (255) NOT NULL COMMENT '',
  `Emp_first_name` (255) NOT NULL COMMENT '',
  `Emp_middle_name` (255) NOT NULL COMMENT '',
  `Email` (255) NOT NULL COMMENT '',
  `Address` (255) NOT NULL COMMENT '',
  `Postal_code` INT(11) NULL DEFAULT NULL COMMENT '',
  `Tel_num` INT(11) NOT NULL COMMENT '',
  `Mobile_num` INT(11) NOT NULL COMMENT '',
  `Gender` (255) NOT NULL COMMENT '',
  `Civil_status` (255) NOT NULL COMMENT '',
  `Birth_date`  NOT NULL COMMENT '',
  `Birth_place` (255) NOT NULL COMMENT '',
  `Religion` (255) NOT NULL COMMENT '',
  `TIN_num` INT(11) NULL DEFAULT NULL COMMENT '',
  `Department_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`Emp_id`)  COMMENT '',
  INDEX `fk_Employee_Department1_idx` (`Department_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`reservation_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`reservation_header` (
  `Reservation_header_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Date_created`  NOT NULL COMMENT '',
  `Scope_of_work` (255) NOT NULL COMMENT '',
  `Emp_id` INT(11) NOT NULL COMMENT '',
  `Department_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`Reservation_header_id`)  COMMENT '',
  INDEX `fk_Reservation for Student Assistant_Employee1_idx` (`Emp_id` ASC)  COMMENT '',
  INDEX `fk_Reservation_header_Department1_idx` (`Department_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Reservation for Student Assistant_Employee1`
    FOREIGN KEY (`Emp_id`)
    REFERENCES `sasystem`.`employee` (`Emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_header_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`student` (
  `Student_id` INT(11) NOT NULL COMMENT '',
  `Student_last_name` (255) NOT NULL COMMENT '',
  `Student_first_name` (255) NOT NULL COMMENT '',
  `Student_middle_name` (255) NOT NULL COMMENT '',
  `Birth_date`  NOT NULL COMMENT '',
  `Birth_place`  NOT NULL COMMENT '',
  `Entry_level` (255) NOT NULL COMMENT '',
  `Nationality` (255) NOT NULL COMMENT '',
  `Gender` (255) NOT NULL COMMENT '',
  `Address` (255) NOT NULL COMMENT '',
  `Postal_code` INT(11) NOT NULL COMMENT '',
  `Tel_num` INT(11) NOT NULL COMMENT '',
  `Mobile_num` INT(11) NOT NULL COMMENT '',
  `Email` (255) NOT NULL COMMENT '',
  `Religion` (255) NOT NULL COMMENT '',
  `Civil_status` (255) NOT NULL COMMENT '',
  PRIMARY KEY (`Student_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`term` (
  `Term_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `school_year` (4) NOT NULL COMMENT '',
  `Term_num` (255) NOT NULL COMMENT '',
  `SA_hours`  NOT NULL COMMENT '',
  `Term_start`  NOT NULL COMMENT '',
  `Term_end`  NOT NULL COMMENT '',
  PRIMARY KEY (`Term_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`student_assistant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`student_assistant` (
  `Student_Assistant_id` INT(11) NOT NULL COMMENT '',
  `Student_id` INT(11) NOT NULL COMMENT '',
  `Term_id` INT(11) NOT NULL COMMENT '',
  `CGPA_status` (255) NOT NULL COMMENT '',
  PRIMARY KEY (`Student_Assistant_id`)  COMMENT '',
  INDEX `fk_Student_has_Scholarship_Student1_idx` (`Student_id` ASC)  COMMENT '',
  INDEX `fk_Student_has_Scholarship_Term1_idx` (`Term_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Student_has_Scholarship_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `sasystem`.`student` (`Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Scholarship_Term1`
    FOREIGN KEY (`Term_id`)
    REFERENCES `sasystem`.`term` (`Term_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`sa_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`sa_record` (
  `Record_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Record_time_in`  NOT NULL COMMENT '',
  `Record_time_out`  NOT NULL COMMENT '',
  `Scope_of_work` (255) NOT NULL COMMENT '',
  `Emp_id` INT(11) NOT NULL COMMENT '',
  `Department_id` INT(11) NOT NULL COMMENT '',
  `Student_Assistant_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`Record_id`)  COMMENT '',
  INDEX `fk_Record of SA Log_Employee1_idx` (`Emp_id` ASC)  COMMENT '',
  INDEX `fk_Record of SA Log_Department1_idx` (`Department_id` ASC)  COMMENT '',
  INDEX `fk_SA_record_Student_scholar1_idx` (`Student_Assistant_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Record of SA Log_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Record of SA Log_Employee1`
    FOREIGN KEY (`Emp_id`)
    REFERENCES `sasystem`.`employee` (`Emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SA_record_Student_scholar1`
    FOREIGN KEY (`Student_Assistant_id`)
    REFERENCES `sasystem`.`student_assistant` (`Student_Assistant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`scholarship` (
  `Scholarship_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Student_Assistant_id` INT(11) NOT NULL COMMENT '',
  `Scholarship_code` (255) NOT NULL COMMENT '',
  `Scholarship_description` (255) NOT NULL COMMENT '',
  `Scholarship_group` (255) NOT NULL COMMENT '',
  `Discount` (10,0) NOT NULL COMMENT '',
  `Waive_fee`  NOT NULL COMMENT '',
  `Scholarship_apply` (255) NOT NULL COMMENT '',
  `Required_GPA` (10,0) NOT NULL COMMENT '',
  `SA_hours` (10,0) NOT NULL COMMENT '',
  `Program_apply` (255) NOT NULL COMMENT '',
  PRIMARY KEY (`Scholarship_id`)  COMMENT '',
  INDEX `fk_Scholarship_Student_Assistant1_idx` (`Student_Assistant_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Scholarship_Student_Assistant1`
    FOREIGN KEY (`Student_Assistant_id`)
    REFERENCES `sasystem`.`student_assistant` (`Student_Assistant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`cobalt_reporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`cobalt_reporter` (
  `module_name` VARCHAR(255) NOT NULL COMMENT '',
  `report_name` VARCHAR(255) NOT NULL COMMENT '',
  `username` VARCHAR(255) NOT NULL COMMENT '',
  `show_field` BLOB NOT NULL COMMENT '',
  `operator` BLOB NOT NULL COMMENT '',
  `text_field` BLOB NOT NULL COMMENT '',
  `sum_field` BLOB NOT NULL COMMENT '',
  `count_field` BLOB NOT NULL COMMENT '',
  `group_field1` BLOB NOT NULL COMMENT '',
  `group_field2` BLOB NOT NULL COMMENT '',
  `group_field3` BLOB NOT NULL COMMENT '',
  PRIMARY KEY (`module_name`, `report_name`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`cobalt_sst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`cobalt_sst` (
  `auto_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `description` VARCHAR(255) NOT NULL COMMENT '',
  `config_file` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`auto_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`person` (
  `person_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(255) NOT NULL COMMENT '',
  `middle_name` VARCHAR(255) NOT NULL COMMENT '',
  `last_name` VARCHAR(255) NOT NULL COMMENT '',
  `gender` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`person_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`request` (
  `Request_id` INT(11) NOT NULL COMMENT '',
  `Student_assistant_id` INT(11) NOT NULL COMMENT '',
  `Department_id` INT(11) NOT NULL COMMENT '',
  `Date_request` DATETIME NOT NULL COMMENT '',
  `Time_in` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `Time_out` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '',
  `Is_approved` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `Date_created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`Request_id`)  COMMENT '',
  INDEX `fk_Request_Student_assistant1_idx` (`Student_assistant_id` ASC)  COMMENT '',
  INDEX `fk_Request_Department1_idx` (`Department_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Request_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `sasystem`.`department` (`Department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Student_assistant1`
    FOREIGN KEY (`Student_assistant_id`)
    REFERENCES `sasystem`.`student_assistant` (`Student_Assistant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`reservation_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`reservation_details` (
  `Reservation_details_id` INT(11) NOT NULL COMMENT '',
  `Reservation_header_id` INT(11) NOT NULL COMMENT '',
  `Student_assistant_id` INT(11) NOT NULL COMMENT '',
  `Date_reserved` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `Time_in` DATETIME NOT NULL COMMENT '',
  `Time_out` DATETIME NOT NULL COMMENT '',
  `Is_approved` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Reservation_details_id`)  COMMENT '',
  INDEX `fk_Reservation_details_Reservation_header1_idx` (`Reservation_header_id` ASC)  COMMENT '',
  INDEX `fk_Reservation_details_Student_assistant1_idx` (`Student_assistant_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Reservation_details_Reservation_header1`
    FOREIGN KEY (`Reservation_header_id`)
    REFERENCES `sasystem`.`reservation_header` (`Reservation_header_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_details_Student_assistant1`
    FOREIGN KEY (`Student_assistant_id`)
    REFERENCES `sasystem`.`student_assistant` (`Student_Assistant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`system_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`system_log` (
  `entry_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `ip_address` VARCHAR(255) NOT NULL COMMENT '',
  `user` VARCHAR(255) NOT NULL COMMENT '',
  `datetime` DATETIME NOT NULL COMMENT '',
  `action` MEDIUMTEXT NOT NULL COMMENT '',
  `module` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`entry_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`system_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`system_settings` (
  `setting` VARCHAR(255) NOT NULL COMMENT '',
  `value` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`setting`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`system_skins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`system_skins` (
  `skin_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `skin_name` VARCHAR(255) NOT NULL COMMENT '',
  `header` VARCHAR(255) NOT NULL COMMENT '',
  `footer` VARCHAR(255) NOT NULL COMMENT '',
  `master_css` VARCHAR(255) NOT NULL COMMENT '',
  `colors_css` VARCHAR(255) NOT NULL COMMENT '',
  `fonts_css` VARCHAR(255) NOT NULL COMMENT '',
  `override_css` VARCHAR(255) NOT NULL COMMENT '',
  `icon_set` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`skin_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`user` (
  `username` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `salt` VARCHAR(255) NOT NULL COMMENT '',
  `iteration` INT(11) NOT NULL COMMENT '',
  `method` VARCHAR(255) NOT NULL COMMENT '',
  `person_id` INT(11) NOT NULL COMMENT '',
  `role_id` INT(11) NOT NULL COMMENT '',
  `skin_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`user_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`user_links` (
  `link_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `target` VARCHAR(255) NOT NULL COMMENT '',
  `descriptive_title` VARCHAR(255) NOT NULL COMMENT '',
  `description` TEXT NOT NULL COMMENT '',
  `passport_group_id` INT(11) NOT NULL COMMENT '',
  `show_in_tasklist` VARCHAR(255) NOT NULL COMMENT '',
  `status` VARCHAR(255) NOT NULL COMMENT '',
  `icon` VARCHAR(255) NOT NULL COMMENT '',
  `priority` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`link_id`)  COMMENT '',
  INDEX `name` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 77
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`user_passport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`user_passport` (
  `username` VARCHAR(255) NOT NULL COMMENT '',
  `link_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`username`, `link_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`user_passport_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`user_passport_groups` (
  `passport_group_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `passport_group` VARCHAR(255) NOT NULL COMMENT '',
  `priority` INT(11) NOT NULL COMMENT '',
  `icon` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`passport_group_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`user_role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `role` VARCHAR(255) NOT NULL COMMENT '',
  `description` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sasystem`.`user_role_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasystem`.`user_role_links` (
  `role_id` INT(11) NOT NULL COMMENT '',
  `link_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`, `link_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
